/**
 * Asking loreserver to create or look up a repository.
 *
 * gRPC is the whole interface. Team never opens a repository's store, and does
 * not link against lore's library to do it: loreserver holds an exclusive lock
 * on a store it is serving, and a second process opening the same directory
 * does not fail — it blocks, with no error and no timeout, for as long as the
 * server it is competing with keeps running.
 *
 * The call carries a token Team minted for the operator, which is the same kind
 * of token a Studio installation presents. loreserver checks its signature and
 * its audience, then turns round and asks Team — over the service in ./service.ts
 * — whether that caller may have what they asked for.
 */
import { randomUUID } from "node:crypto";

import { unaryCall } from "../grpc/client.js";
import {
  decodeRepositoryResponse,
  encodeRepositoryCreateRequest,
  encodeRepositoryGetRequest,
  METHOD_REPOSITORY_CREATE,
  METHOD_REPOSITORY_GET,
  type Repository,
  type RepositoryQuery,
} from "../grpc/messages.js";
import { GRPC_INTERNAL, GrpcStatusError } from "../grpc/status.js";

/** The branch a repository is created with when the caller names none. */
export const DEFAULT_BRANCH_NAME = "main";

/** Where loreserver serves gRPC, given the port it was configured with. */
export function loreserverUrl(dataPort: number, host = "127.0.0.1"): string {
  return `http://${host}:${dataPort}`;
}

/**
 * A sixteen-byte identifier as lower-case hex.
 *
 * loreserver has the caller generate both the repository id and the default
 * branch id so that a retried create is the same repository rather than a
 * second one.
 */
function newIdentifier(): string {
  return randomUUID().replaceAll("-", "");
}

/** What creating a repository needs. */
export interface RepositoryCreateOptions {
  /** Where loreserver is, from {@link loreserverUrl}. */
  readonly url: string;
  /** The token to present, as the value of an `authorization: Bearer` header. */
  readonly token: string;
  /** The repository id, generated by the caller. */
  readonly id: string;
  readonly name: string;
  readonly description?: string;
  readonly defaultBranchName?: string;
  readonly timeoutMs?: number;
}

function repositoryOrFail(message: Buffer, path: string): Repository {
  const repository = decodeRepositoryResponse(message);
  if (repository === undefined) {
    throw new GrpcStatusError(
      GRPC_INTERNAL,
      `${path} answered without a repository, which is the one field its reply carries`,
    );
  }
  return repository;
}

/** Create a repository, and return the record loreserver made. */
export async function repositoryCreate(options: RepositoryCreateOptions): Promise<Repository> {
  const message = encodeRepositoryCreateRequest({
    id: options.id,
    name: options.name,
    description: options.description ?? "",
    defaultBranchId: newIdentifier(),
    defaultBranchName: options.defaultBranchName ?? DEFAULT_BRANCH_NAME,
    // `creator` is left out, so loreserver attributes the repository to the
    // identity in the token. Naming somebody else needs a permission of its own.
  });

  const reply = await unaryCall({
    url: options.url,
    path: METHOD_REPOSITORY_CREATE,
    message,
    authorization: `Bearer ${options.token}`,
    ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }),
  });
  return repositoryOrFail(reply, METHOD_REPOSITORY_CREATE);
}

/** What looking a repository up needs. */
export interface RepositoryGetOptions {
  readonly url: string;
  readonly token: string;
  readonly query: RepositoryQuery;
  readonly timeoutMs?: number;
}

/**
 * Look a repository up by id or by name.
 *
 * This is the call that goes through the permission check: loreserver asks Team
 * about the repository before it answers, and a caller with no grant is told
 * the repository does not exist rather than that they may not have it.
 */
export async function repositoryGet(options: RepositoryGetOptions): Promise<Repository> {
  const reply = await unaryCall({
    url: options.url,
    path: METHOD_REPOSITORY_GET,
    message: encodeRepositoryGetRequest(options.query),
    authorization: `Bearer ${options.token}`,
    ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }),
  });
  return repositoryOrFail(reply, METHOD_REPOSITORY_GET);
}
